"""
ForgeSquad — AutoGen Multi-Agent Implementation

Defines all 9 agents with their system prompts, tools, and configurations.
Implements GroupChat with phase-specific speaker selection and pipeline execution.
"""

import os
import hashlib
import json
import logging
from datetime import datetime, timezone
from typing import Any

from autogen_agentchat.agents import AssistantAgent, UserProxyAgent
from autogen_agentchat.teams import RoundRobinGroupChat, SelectorGroupChat
from autogen_agentchat.conditions import TextMentionTermination, MaxMessageTermination
from autogen_agentchat.messages import TextMessage
from autogen_ext.models.openai import AzureOpenAIChatCompletionClient

from .approval_gate import ApprovalGate, ApprovalRequest

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Model Clients
# ---------------------------------------------------------------------------

def create_premium_client() -> AzureOpenAIChatCompletionClient:
    """Creates Azure OpenAI client for GPT-4o (premium tier)."""
    return AzureOpenAIChatCompletionClient(
        azure_deployment=os.getenv("AZURE_OPENAI_GPT4O_DEPLOYMENT", "forgesquad-gpt4o"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT", ""),
        api_key=os.getenv("AZURE_OPENAI_API_KEY", ""),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-08-01-preview"),
        model="gpt-4o",
        temperature=0.2,
    )


def create_standard_client() -> AzureOpenAIChatCompletionClient:
    """Creates Azure OpenAI client for GPT-4o-mini (standard tier)."""
    return AzureOpenAIChatCompletionClient(
        azure_deployment=os.getenv("AZURE_OPENAI_GPT4O_MINI_DEPLOYMENT", "forgesquad-gpt4o-mini"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT", ""),
        api_key=os.getenv("AZURE_OPENAI_API_KEY", ""),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-08-01-preview"),
        model="gpt-4o-mini",
        temperature=0.3,
    )


# ---------------------------------------------------------------------------
# Tool Functions
# ---------------------------------------------------------------------------

async def generate_c4_diagram(description: str, level: str = "container") -> str:
    """Generates a C4 Model diagram from a system description.

    Args:
        description: Description of the system to diagram.
        level: C4 level — context, container, component, or code.

    Returns:
        Mermaid diagram code for the requested C4 level.
    """
    templates = {
        "context": """
C4Context
    title System Context Diagram
    Person(user, "User", "System user")
    System(system, "Target System", "System under design")
    System_Ext(ext1, "External System 1", "Integration point")
    Rel(user, system, "Uses")
    Rel(system, ext1, "Integrates with")
""",
        "container": """
C4Container
    title Container Diagram
    Person(user, "User")
    Container_Boundary(system, "System") {
        Container(web, "Web App", "React", "Frontend SPA")
        Container(api, "API", ".NET 8", "REST API")
        Container(worker, "Worker", ".NET 8", "Background processing")
        ContainerDb(db, "Database", "PostgreSQL", "Primary store")
        ContainerDb(cache, "Cache", "Redis", "Caching layer")
    }
    Rel(user, web, "Uses", "HTTPS")
    Rel(web, api, "Calls", "HTTPS/JSON")
    Rel(api, db, "Reads/Writes")
    Rel(api, cache, "Reads/Writes")
""",
    }
    diagram = templates.get(level, templates["container"])
    return f"## C4 Diagram — {level} level\n\n```mermaid\n{diagram}\n```\n"


async def create_adr(title: str, context: str, decision: str, consequences: str) -> str:
    """Creates an Architecture Decision Record (ADR).

    Args:
        title: Title of the architectural decision.
        context: Context explaining why this decision is needed.
        decision: The chosen option and justification.
        consequences: Positive and negative consequences.

    Returns:
        Formatted ADR document in Markdown.
    """
    adr_number = datetime.now(timezone.utc).strftime("%Y%m%d%H%M")
    return f"""# ADR-{adr_number}: {title}

**Date:** {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
**Status:** Proposed

## Context
{context}

## Decision
{decision}

## Consequences
{consequences}

---
*Generated by ForgeSquad Architect Agent*
"""


async def validate_compliance(
    artifact: str,
    regulation: str = "all",
) -> str:
    """Validates an artifact against financial regulations.

    Args:
        artifact: Description of the artifact to validate.
        regulation: Regulation to check — bacen_4893, lgpd, bian, or all.

    Returns:
        Compliance validation report.
    """
    checks = {
        "bacen_4893": [
            ("Cybersecurity Policy", "Pending", "High"),
            ("Incident Response Plan", "Pending", "Critical"),
            ("Periodic Risk Assessment", "Pending", "High"),
        ],
        "lgpd": [
            ("Legal Basis Defined", "Pending", "Critical"),
            ("Data Subject Rights", "Pending", "High"),
            ("Breach Notification Process", "Pending", "High"),
            ("DPIA Assessment", "Pending", "Medium"),
        ],
        "bian": [
            ("Service Domain Mapping", "Pending", "Medium"),
            ("Service Operations Alignment", "Pending", "Medium"),
        ],
    }

    report = "## Compliance Validation Report\n\n"
    report += f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')}\n"
    report += f"**Regulation:** {regulation}\n\n"
    report += "| Requirement | Status | Risk |\n|---|---|---|\n"

    selected = checks if regulation == "all" else {regulation: checks.get(regulation, [])}
    for reg, items in selected.items():
        for req, status, risk in items:
            report += f"| [{reg}] {req} | {status} | {risk} |\n"

    return report


async def check_tech_radar(technology: str) -> str:
    """Checks if a technology is approved in the company Tech Radar.

    Args:
        technology: Name of the technology to check.

    Returns:
        Tech Radar status and recommendation.
    """
    radar = {
        "C#": ("Adopt", "Primary backend language"),
        "PostgreSQL": ("Adopt", "Primary relational database"),
        "React": ("Adopt", "Primary frontend framework"),
        "Kafka": ("Adopt", "Event streaming platform"),
        "Redis": ("Adopt", "Caching layer"),
        "MongoDB": ("Trial", "Document-oriented workloads"),
        "GraphQL": ("Trial", "BFF scenarios"),
        "Angular": ("Hold", "Legacy support only"),
    }
    if technology in radar:
        ring, notes = radar[technology]
        return f"**{technology}** — Ring: {ring} | Notes: {notes}"
    return f"**{technology}** — Not in Tech Radar. Requires Architecture Board approval."


async def create_user_stories(domain_context: str) -> str:
    """Generates user stories template based on domain context.

    Args:
        domain_context: Domain analysis output to base stories on.

    Returns:
        User story template with Gherkin acceptance criteria.
    """
    return f"""## User Stories

Based on domain analysis:
{domain_context[:500]}...

### Template
**US-001:** As a [role], I want [feature], so that [benefit]

**Acceptance Criteria (Gherkin):**
```gherkin
Given [precondition]
When [action]
Then [expected result]
```

*The BA agent will generate specific stories based on the domain analysis.*
"""


async def generate_test_plan(requirements: str) -> str:
    """Generates a test plan based on requirements.

    Args:
        requirements: Requirements and acceptance criteria to cover.

    Returns:
        Test plan with strategy and coverage targets.
    """
    return f"""## Test Plan

### Test Strategy
- Unit Tests: >80% code coverage
- Integration Tests: All API endpoints
- E2E Tests: Critical user journeys
- Performance Tests: Response time SLOs

### Coverage Requirements
{requirements[:500]}...

### Test Types
| Type | Tool | Target |
|------|------|--------|
| Unit | xUnit / Jest | >80% coverage |
| Integration | TestContainers | All APIs |
| E2E | Playwright | Critical paths |
| Performance | k6 | P95 < 200ms |
| Security | OWASP ZAP | No critical findings |

*The QA agent will detail specific test cases.*
"""


# ---------------------------------------------------------------------------
# Agent Definitions
# ---------------------------------------------------------------------------

ARCHITECT_PROMPT = """You are the **Architect** of ForgeSquad, the most senior technical agent.

You participate in EVERY phase. Responsibilities:
1. System architecture design (Hexagonal, Microservices, Event-Driven, CQRS)
2. Architecture Decision Records (ADRs) — document all key decisions
3. Technical validation of all artifacts from other agents
4. Technology governance via Tech Radar
5. Quality gates at every phase

Decision framework: Context → Options (min 3) → Decision → Consequences → Status
Always consider NFRs: performance, security, scalability, observability.
When you reach a final decision, state "DECIDED:" clearly.

You have tools: generate_c4_diagram, create_adr, check_tech_radar, validate_compliance"""

TECH_LEAD_PROMPT = """You are the **Tech Lead** of ForgeSquad.

Responsibilities:
1. Technical coordination and code standards
2. Sprint planning and task breakdown
3. Code review — enforce SOLID, clean code, test coverage
4. CI/CD pipeline configuration
5. Bridge between Architect's vision and dev execution

Focus on: practical implementation, team productivity, technical debt.
When reviewing code, provide specific, actionable feedback."""

BA_PROMPT = """You are the **Business Analyst** of ForgeSquad.

Responsibilities:
1. Requirements elicitation and documentation
2. User stories in format: As a [role], I want [feature], so that [benefit]
3. Acceptance criteria in Gherkin (Given/When/Then)
4. Domain analysis using DDD (bounded contexts, entities, events)
5. Product backlog management

You have tools: create_user_stories"""

DEV_BACKEND_PROMPT = """You are the **Backend Developer** of ForgeSquad.

Responsibilities:
1. API design (REST/GraphQL) with OpenAPI specs
2. Database schema design and migrations
3. Business logic implementation following Clean Architecture
4. Unit and integration tests (>80% coverage)
5. Integration with external services

Stack: C# / .NET 8, PostgreSQL, Redis, Kafka, Docker
Follow SOLID principles. Never hardcode credentials."""

DEV_FRONTEND_PROMPT = """You are the **Frontend Developer** of ForgeSquad.

Responsibilities:
1. UI component design and implementation
2. Responsive design and accessibility (WCAG 2.1)
3. State management and API integration
4. Component and E2E tests
5. Performance optimization

Stack: React / Next.js, TypeScript, Tailwind CSS, Storybook"""

QA_PROMPT = """You are the **QA Engineer** of ForgeSquad.

Responsibilities:
1. Test strategy and planning
2. Automated test creation (unit, integration, E2E, performance)
3. Acceptance criteria validation with edge cases
4. Quality metrics tracking (coverage, defect density)
5. Regression and performance testing

Target: >80% code coverage, zero critical defects.
You have tools: generate_test_plan"""

TECH_WRITER_PROMPT = """You are the **Tech Writer** of ForgeSquad.

Responsibilities:
1. API documentation with examples
2. Architecture Decision Records (ADRs)
3. Operational runbooks and playbooks
4. Onboarding guides
5. Docs-as-Code approach

Write clear, concise, well-structured documentation."""

PM_PROMPT = """You are the **Project Manager** of ForgeSquad.

Responsibilities:
1. Stakeholder mapping and communication
2. Progress tracking and status reports
3. Risk identification and mitigation
4. Sprint metrics (velocity, burndown)
5. Retrospective facilitation

Produce actionable reports with clear metrics and next steps."""

FINANCE_ADVISOR_PROMPT = """You are the **Finance Advisor** of ForgeSquad.

Specialist in regulatory compliance for financial technology:
1. Bacen (4893 cybersecurity, 4658 cloud, Open Finance)
2. BIAN Service Landscape alignment
3. Basel III/IV capital and risk requirements
4. LGPD data protection
5. SOX internal controls, PCI-DSS

Always cite specific regulation articles. Recommend conservative approach when in doubt.
You have tools: validate_compliance"""


def create_all_agents() -> dict[str, AssistantAgent]:
    """Creates all 9 ForgeSquad agents with appropriate model clients and tools."""

    premium = create_premium_client()
    standard = create_standard_client()

    agents = {}

    # Premium tier (GPT-4o) — complex reasoning
    agents["Architect"] = AssistantAgent(
        name="Architect",
        model_client=premium,
        system_message=ARCHITECT_PROMPT,
        tools=[generate_c4_diagram, create_adr, check_tech_radar, validate_compliance],
    )

    agents["TechLead"] = AssistantAgent(
        name="TechLead",
        model_client=premium,
        system_message=TECH_LEAD_PROMPT,
    )

    agents["DevBackend"] = AssistantAgent(
        name="DevBackend",
        model_client=premium,
        system_message=DEV_BACKEND_PROMPT,
    )

    agents["DevFrontend"] = AssistantAgent(
        name="DevFrontend",
        model_client=premium,
        system_message=DEV_FRONTEND_PROMPT,
    )

    agents["FinanceAdvisor"] = AssistantAgent(
        name="FinanceAdvisor",
        model_client=premium,
        system_message=FINANCE_ADVISOR_PROMPT,
        tools=[validate_compliance],
    )

    # Standard tier (GPT-4o-mini) — support agents
    agents["BA"] = AssistantAgent(
        name="BusinessAnalyst",
        model_client=standard,
        system_message=BA_PROMPT,
        tools=[create_user_stories],
    )

    agents["QA"] = AssistantAgent(
        name="QAEngineer",
        model_client=standard,
        system_message=QA_PROMPT,
        tools=[generate_test_plan],
    )

    agents["TechWriter"] = AssistantAgent(
        name="TechWriter",
        model_client=standard,
        system_message=TECH_WRITER_PROMPT,
    )

    agents["PM"] = AssistantAgent(
        name="ProjectManager",
        model_client=standard,
        system_message=PM_PROMPT,
    )

    return agents


# ---------------------------------------------------------------------------
# Pipeline Definition
# ---------------------------------------------------------------------------

PIPELINE_PHASES = [
    {
        "number": 1,
        "name": "Discovery",
        "agents": ["PM", "BA", "Architect"],
        "steps": [
            {"name": "Stakeholder Mapping", "agent": "PM"},
            {"name": "Domain Analysis", "agent": "BA"},
            {"name": "Feasibility Check", "agent": "Architect"},
        ],
        "checkpoint": {"enabled": True, "number": 1},
        "max_rounds": 12,
    },
    {
        "number": 2,
        "name": "Requirements",
        "agents": ["BA", "Architect", "QA"],
        "steps": [
            {"name": "User Stories", "agent": "BA"},
            {"name": "Acceptance Criteria", "agent": "QA"},
            {"name": "Requirements Review", "agent": "Architect"},
        ],
        "checkpoint": {"enabled": True, "number": 2},
        "max_rounds": 12,
    },
    {
        "number": 3,
        "name": "Architecture",
        "agents": ["Architect", "TechLead", "FinanceAdvisor"],
        "steps": [
            {"name": "Solution Design", "agent": "Architect"},
            {"name": "ADR Creation", "agent": "Architect"},
        ],
        "checkpoint": {"enabled": True, "number": 3},
        "max_rounds": 10,
    },
    {
        "number": 4,
        "name": "Planning",
        "agents": ["TechLead", "PM"],
        "steps": [
            {"name": "Sprint Planning", "agent": "TechLead"},
            {"name": "Task Breakdown", "agent": "TechLead"},
        ],
        "checkpoint": {"enabled": True, "number": 4},
        "max_rounds": 8,
    },
    {
        "number": 5,
        "name": "Backend Development",
        "agents": ["DevBackend", "TechLead", "Architect"],
        "steps": [
            {"name": "API Design", "agent": "DevBackend"},
            {"name": "Implementation", "agent": "DevBackend"},
            {"name": "Code Review", "agent": "TechLead"},
        ],
        "checkpoint": {"enabled": True, "number": 5},
        "max_rounds": 15,
    },
    {
        "number": 6,
        "name": "Frontend Development",
        "agents": ["DevFrontend", "TechLead"],
        "steps": [
            {"name": "UI Design", "agent": "DevFrontend"},
            {"name": "Implementation", "agent": "DevFrontend"},
            {"name": "Integration", "agent": "DevFrontend"},
        ],
        "checkpoint": {"enabled": True, "number": 6},
        "max_rounds": 15,
    },
    {
        "number": 7,
        "name": "QA",
        "agents": ["QA", "DevBackend", "DevFrontend"],
        "steps": [
            {"name": "Test Strategy", "agent": "QA"},
            {"name": "Test Execution", "agent": "QA"},
        ],
        "checkpoint": {"enabled": True, "number": 7},
        "max_rounds": 10,
    },
    {
        "number": 8,
        "name": "Documentation",
        "agents": ["TechWriter", "Architect"],
        "steps": [
            {"name": "API Documentation", "agent": "TechWriter"},
            {"name": "Runbooks & ADRs", "agent": "TechWriter"},
        ],
        "checkpoint": {"enabled": True, "number": 8},
        "max_rounds": 8,
    },
    {
        "number": 9,
        "name": "Deployment",
        "agents": ["TechLead", "DevBackend", "QA"],
        "steps": [
            {"name": "CI/CD Pipeline", "agent": "TechLead"},
            {"name": "Production Deploy", "agent": "TechLead"},
        ],
        "checkpoint": {"enabled": True, "number": 9},
        "max_rounds": 10,
    },
    {
        "number": 10,
        "name": "Retrospective",
        "agents": ["PM", "Architect"],
        "steps": [
            {"name": "Metrics Collection", "agent": "PM"},
            {"name": "Lessons Learned", "agent": "PM"},
        ],
        "checkpoint": {"enabled": False},
        "max_rounds": 8,
    },
]


# ---------------------------------------------------------------------------
# Pipeline Execution
# ---------------------------------------------------------------------------

class ForgeSquadPipeline:
    """Orchestrates the ForgeSquad multi-agent pipeline using AutoGen GroupChat."""

    def __init__(self, auto_approve: bool = False):
        self.agents = create_all_agents()
        self.approval_gate = ApprovalGate(auto_approve=auto_approve)
        self.run_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        self.audit_trail: list[dict[str, Any]] = []
        self.accumulated_context: dict[str, str] = {}

    async def execute(
        self,
        project_name: str,
        project_description: str,
        skip_phases: list[int] | None = None,
    ) -> dict[str, Any]:
        """Executes the full ForgeSquad pipeline."""

        logger.info("Pipeline %s started for project: %s", self.run_id, project_name)
        self.accumulated_context["ProjectName"] = project_name
        self.accumulated_context["ProjectDescription"] = project_description

        self._log_event("PipelineStarted", "N/A", "Pipeline",
                        f"Started for project: {project_name}")

        results: list[dict[str, Any]] = []

        for phase in PIPELINE_PHASES:
            if skip_phases and phase["number"] in skip_phases:
                logger.info("Skipping phase %d: %s", phase["number"], phase["name"])
                continue

            phase_result = await self._execute_phase(phase)
            results.append(phase_result)

            if phase_result.get("status") == "rejected":
                logger.warning("Pipeline paused at phase %s", phase["name"])
                return {
                    "run_id": self.run_id,
                    "status": "paused",
                    "paused_at": phase["name"],
                    "phases": results,
                    "audit_trail": self.audit_trail,
                }

        self._log_event("PipelineCompleted", "N/A", "Pipeline", "Completed successfully")

        return {
            "run_id": self.run_id,
            "status": "completed",
            "phases": results,
            "audit_trail": self.audit_trail,
        }

    async def _execute_phase(self, phase: dict) -> dict[str, Any]:
        """Executes a single pipeline phase using SelectorGroupChat."""

        phase_name = phase["name"]
        phase_number = phase["number"]
        logger.info("Starting phase %d: %s", phase_number, phase_name)

        self._log_event("PhaseStarted", phase_name,
                        ", ".join(phase["agents"]),
                        f"Phase {phase_number}: {phase_name}")

        # Select agents for this phase
        phase_agents = [self.agents[a] for a in phase["agents"] if a in self.agents]

        if not phase_agents:
            raise ValueError(f"No agents found for phase {phase_name}")

        # Build initial message with context
        initial_message = self._build_phase_prompt(phase)

        # Create group chat with selector (LLM-based speaker selection)
        termination = MaxMessageTermination(max_messages=phase.get("max_rounds", 10))

        team = SelectorGroupChat(
            participants=phase_agents,
            model_client=create_standard_client(),  # Selector uses cheaper model
            termination_condition=termination,
            selector_prompt=(
                "You are managing a software engineering squad discussion. "
                "Based on the conversation so far, select the next speaker. "
                f"Available speakers: {', '.join(phase['agents'])}. "
                "Follow this order for the current phase steps: "
                f"{', '.join(s['agent'] for s in phase['steps'])}. "
                "Return ONLY the speaker name."
            ),
        )

        # Run the group chat
        output_messages: list[str] = []
        async for message in team.run_stream(task=initial_message):
            if hasattr(message, "content") and message.content:
                output_messages.append(f"**{getattr(message, 'source', 'System')}:** {message.content}")
                logger.debug("[%s] %s: %s",
                             phase_name,
                             getattr(message, "source", "?"),
                             message.content[:100])

        phase_output = "\n\n".join(output_messages)
        output_hash = hashlib.sha256(phase_output.encode()).hexdigest()

        # Store in accumulated context
        self.accumulated_context[f"{phase_name}_output"] = phase_output

        self._log_event("PhaseExecuted", phase_name, "GroupChat",
                        f"Phase completed with {len(output_messages)} messages",
                        artifact_hash=output_hash)

        # Handle checkpoint
        checkpoint = phase.get("checkpoint", {})
        if checkpoint.get("enabled"):
            cp_number = checkpoint["number"]
            logger.info("Checkpoint %d reached", cp_number)

            approval = await self.approval_gate.request_approval(
                ApprovalRequest(
                    run_id=self.run_id,
                    checkpoint_number=cp_number,
                    phase_name=phase_name,
                    artifact_summary=phase_output[:2000],
                    artifact_hash=output_hash,
                )
            )

            self._log_event(
                "CheckpointDecided", phase_name, approval.decided_by,
                f"Checkpoint {cp_number}: {approval.decision}",
            )

            if approval.decision == "rejected":
                return {
                    "phase": phase_name,
                    "number": phase_number,
                    "status": "rejected",
                    "checkpoint": cp_number,
                    "output": phase_output,
                }

        return {
            "phase": phase_name,
            "number": phase_number,
            "status": "completed",
            "output": phase_output,
            "output_hash": output_hash,
            "messages": len(output_messages),
        }

    def _build_phase_prompt(self, phase: dict) -> str:
        """Builds the initial prompt for a phase with accumulated context."""

        prompt = f"## Phase {phase['number']}: {phase['name']}\n\n"
        prompt += "### Steps to execute:\n"
        for i, step in enumerate(phase["steps"], 1):
            prompt += f"{i}. **{step['name']}** (lead: {step['agent']})\n"

        prompt += f"\n### Project: {self.accumulated_context.get('ProjectName', 'Unknown')}\n"
        prompt += f"### Description: {self.accumulated_context.get('ProjectDescription', 'N/A')}\n"

        # Add relevant context from previous phases
        for key, value in self.accumulated_context.items():
            if key.endswith("_output") and len(value) > 0:
                phase_label = key.replace("_output", "")
                prompt += f"\n### Context from {phase_label}:\n"
                prompt += value[:1500] + ("\n... (truncated)" if len(value) > 1500 else "")
                prompt += "\n"

        prompt += "\nPlease collaborate to complete all steps for this phase. "
        prompt += "Each agent should contribute according to their expertise.\n"

        return prompt

    def _log_event(
        self,
        event_type: str,
        phase: str,
        agent: str,
        message: str,
        artifact_hash: str | None = None,
    ) -> None:
        """Logs an audit event."""
        event = {
            "run_id": self.run_id,
            "event_type": event_type,
            "phase": phase,
            "agent": agent,
            "message": message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "artifact_hash": artifact_hash,
        }
        # Chain hash for integrity
        prev_hash = self.audit_trail[-1].get("event_hash", "genesis") if self.audit_trail else "genesis"
        content = f"{event['run_id']}|{event_type}|{phase}|{agent}|{message}|{prev_hash}"
        event["event_hash"] = hashlib.sha256(content.encode()).hexdigest()
        event["previous_hash"] = prev_hash

        self.audit_trail.append(event)
        logger.info("[AUDIT] %s | %s | %s | %s", event_type, phase, agent, message)
